### ISSUE TITLE
Sort and Filter option for the material page

### ISSUE THREAD

**Issue by squaresmile** [atlasacademy/apps#16]
https://apps.atlasacademy.io/db/JP/item/6508
- Sort by number of mats required
- Filter only servants that use the mat for skills for example since append/costume usage clutters up the table

**Comment by minhducsun2002** [comment]
Closing with 53e2534e34f5feb6b8e152d75088d60bc3fb8c41 and a4b3c1a7271b4b48bf93a08ccb8cb9f21ae796b3.
