### ISSUE TITLE
Toggle to hide "enemy" functions

### ISSUE THREAD

**Issue by squaresmile** [atlasacademy/apps#18]
Some test cases:
https://apps.atlasacademy.io/db/JP/servant/309/skill-3
https://apps.atlasacademy.io/db/JP/servant/263/skill-2
https://apps.atlasacademy.io/db/JP/servant/236/noble-phantasms
https://apps.atlasacademy.io/db/NA/ai/svt/94041836?skillId1=60451&skillId2=227553&skillId3=228350

**Comment by minhducsun2002** [comment]
Closed in 3efeee9e8c1af5692723bbc96fb1e6e04557a614.
