### ISSUE TITLE
Add filter by buff in craft essence page.

### ISSUE THREAD

**Issue by O-Isaac** [atlasacademy/apps#34]
Filter craft essence by buster up, np dmg up, crit up, guts, etc...

**Comment by squaresmile** [comment]
This would require fetching the heavier [nice equip](https://api.atlasacademy.io/export/JP/nice_equip_lang_en.json) instead of the [basic equip](https://api.atlasacademy.io/export/JP/basic_equip_lang_en.json) so I'm not sure if it's worth it.
