### ISSUE TITLE
Noble Phantasm search link uses incorrect query

### ISSUE THREAD

**Issue by Ylimegirl** [atlasacademy/apps#68]
When looking at a Noble Phantasm that's used in more than 10 quests, such as [this one](https://apps.atlasacademy.io/db/JP/noble-phantasm/247) I picked at random, clicking the "other quests" link sends you to a page [like this one](https://apps.atlasacademy.io/db/JP/quests?enemySkillId=247) where the URL query uses `enemySkillId=` instead of `enemyNoblePhantasmId=`, inevitably always resulting in there being no quest results. Not a huge headache for a user to fix on their end (just copypaste the query from one input box to another), but definitely an oversight that I thought I should mention.

**Comment by squaresmile** [comment]
Thanks for report. I have fixed it.
