### ISSUE TITLE
AI Allocations

### ISSUE THREAD

**Issue by Ylimegirl** [atlasacademy/apps#70]
Not sure if this has been something that's been featured in other quests up until now, but I noticed it being an oversight with the latest Ordeal Call quests.

Basically: category of AI that is stored in a new location(?) in JSONs that applies itself to a specific individuality (so it'll work whether the servant in question is the NPC support or the player's own).

For example, in [Section 12, Phase 6](https://apps.atlasacademy.io/db/JP/quest/4000312/6) of OC2, this snippet of code is hiding in the JSON:
```json
        "aiAllocations": [
          {
            "aiIds": [
              400700
            ],
            "applySvtType": 5,
            "individuality": 1101500
          }
```
This allocates the Servant AI [400700](https://apps.atlasacademy.io/db/JP/AI/svt/400700) to the entity with the ID [1101500](https://apps.atlasacademy.io/db/JP/servant/1101500) -- which in this case is the Nitocris Alter in the player's party, whether it's the support NPC or not.

Currently the AADB has no method of supporting this type of AI connection, meaning that it doesn't show up unless viewing the JSON data of the original quest _and_ that no related quests show up for the AI on its page.

**Comment by squaresmile** [comment]
Fixed with https://github.com/atlasacademy/apps/commit/10354198250b26d9650a7c0375698de660585ed3 and https://github.com/atlasacademy/fgo-game-data-api/commit/c259da9b39e0c3392a0fbfeb98ad31b93ee49eb5
